# NumPy: Fundamental Package for Scientific Computing

## Basic Operations
### Array Creation and Definition
- Create arrays from Python lists
- Specify array dimensions and data types

### Array Slicing
- Extract specific elements
- Access multi-dimensional array elements
- Syntax: `array[start:stop:step]`

### Array Filtering
- Boolean indexing
- Conditional selection
- Create masks for data filtering

### Mathematical Operations
- Element-wise operations
- Array aggregations (sum, mean, etc.)
- Universal functions (ufuncs)

## Advanced Features
### Broadcasting
- Perform operations between arrays of different shapes
- Automatic array shape compatibility
- Efficient memory usage

### Random Number Generation
- Generate uniform distributions
- Create random integers
- Sample from various probability distributions

In [8]:
import numpy as np

# Definition - Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Slicing
print("Slicing examples:")
print(arr1[1:4])  # [2 3 4]
print(arr2[:,:1])  # [[1][4]]


Slicing examples:
[2 3 4]
[[1]
 [4]]


In [ ]:

# Filtering
print("\nFiltering examples:")
mask = arr2 > 2
print(arr2[mask])  # [3 4 5 6]

num = np.where(arr2 > 2, arr2, 0) # Replace elements not greater than 2 with 0
print(num)  # [[0 0 3][4 5 6]]


Filtering examples:
[3 4 5 6]
[[0 0 3]
 [4 5 6]]


In [26]:
# Operations
print("\nOperation examples:")
print(arr1 * 2)  # Element-wise multiplication
print(arr1.sum())  # Sum of all elements



Operation examples:
[ 2  4  6  8 10]
15


In [ ]:
# Broadcasting

print("\nBroadcasting example:")
arr3 = np.array([[1], [2], [3]])
print(arr3 * np.array([1, 2, 3])) # * can be replaced with +, -, /, etc.



Broadcasting example:
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [31]:
# Random numbers
print("\nRandom number examples:")
random_arr = np.random.rand(3, 3)  # 3x3 random array
random_ints = np.random.randint(0, 10, size=5)  # 5 random integers between 0-9

print(random_arr)
print(random_ints)


Random number examples:
[[0.74618263 0.1353296  0.15470247]
 [0.99206858 0.91974193 0.74019185]
 [0.76402365 0.40027293 0.19638277]]
[3 0 6 0 6]


In [3]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x)) 
    return exp_x / np.sum(exp_x)

print(softmax(np.array([0,1,2])))
print(softmax(np.array([10,11,12])))

[0.09003057 0.24472847 0.66524096]
[0.09003057 0.24472847 0.66524096]


## Matrix Operations

### Dot Product

* Definition: $\text{dot}(a,b) = \sum_i a_i b_i$
* Vector dot product and matrix multiplication
* NumPy: `np.dot(a, b)` or `a @ b`

### Matrix Multiplication (`matmul`)

* Equivalent to `@` operator
* Follows standard linear algebra rules
* NumPy: `np.matmul(A, B)` or `A @ B`

### Norms

* **L2 norm (Euclidean length)**:
  $\|x\|_2 = \sqrt{\sum_i x_i^2}$
  NumPy: `np.linalg.norm(x)`
* **L1 norm (Manhattan distance)**:
  $\|x\|_1 = \sum_i |x_i|$
  NumPy: `np.linalg.norm(x, ord=1)`



## Array Manipulation

### Reshape

* Change array shape without changing data
* NumPy: `x.reshape(new_shape)`
* Example: `(2,3) → (3,2)`

### Random Number Generation

* Uniform distribution: `np.random.rand(m,n)`
* Normal distribution: `np.random.randn(m,n)`
* Random integers: `np.random.randint(low, high, size)`



## Softmax

### Definition

$$
\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}
$$

* Converts scores → probability distribution
* Invariant to adding same constant to all inputs



In [6]:

import numpy as np
def softmax(x, axis=-1):
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

print(softmax(np.array([[0,1,2],[10,11,12]]), axis=1))


[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]
